version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tarjuman-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tarjuman
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: tarjuman_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tarjuman -d tarjuman_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
